name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          user_name: OpenBytes-Bot
          user_email: 0xOpenBytes@gmail.com
          publish_dir: dist
          publish_branch: gh-pages
          cname: openbytes.dev
